### ISSUE TITLE
Feature: ajax upload for avatar

### ISSUE THREAD

**Issue by 810** [Kunena/Kunena-Forum#3885]
#### Tasks to do
- [x] Allow to add only one image in the form
- [x] Prevent to add files
- [x] Pre-load the avatar on edit
- [ ] Preview the avatar with a circle
- [x] Finish to implement in controller the part which handle the remove of avatar image in ajax
- [x] Enable drag & drop
- [ ] When user click on avatar, it should go directly to edit profile and open the tab to change avatar
- [ ] Let users to choose an image from the gallery

## 
#### Expected result

Ajax upload for avatar
#### Actual result

none
#### System information (as much as possible)

Joomla version: 
Kunena version:
Php version:
Database version:

**Comment by sshcli** [comment]
Before close this issue, please make sure the following problem has been solved: https://github.com/Kunena/Kunena-Forum/issues/4500

**Comment by 810** [comment]
@xillibit is the pr ready?

**Comment by xillibit** [comment]
Not yet, i will add on the issue the items that are missing

**Comment by xillibit** [comment]
@810 : are-you able to add the preview as circle on avatar ?

**Comment by 810** [comment]
i can't see the avatar now.

could you recheck it on the lasted changes

**Comment by xillibit** [comment]
I will look in the evening

**Comment by rich20** [comment]
- [x] Allow to add only one image in the form
- [x] Prevent to add files
- [x] Pre-load the avatar on edit
- [ ] Preview the avatar with a circle
- [x] Finish to implement in controller the part which handle the remove of avatar image in ajax
- [x] Enable drag & drop
- [x] When user click on avatar, it should go directly to edit profile <strike>and open the tab to change avatar</strike> (The link goes directly to the profile edit but you need a click on the tab to open the avatar options. For me it's ok.)
- [ ] Index page - Click on avatar goes only to the profile
- [x] Other pages - Click goes directly to profile edit
- [ ] Let users to choose an image from the gallery

**Comment by rich20** [comment]
- [x] Allow to add only one image in the form
- [x] Prevent to add files
- [x] Pre-load the avatar on edit
- [ ] Preview the avatar with a circle
- [x] Finish to implement in controller the part which handle the remove of avatar image in ajax
- [x] Enable drag & drop
- [x] When user click on avatar, it should go directly to edit profile <strike>and open the tab to change avatar</strike> (The link goes directly to the profile edit but you need a click on the tab to open the avatar options. For me it's ok.)
- [x] Index page - Click goes directly to profile edit
- [x] Other pages - Click goes directly to profile edit
- [ ] Let users to choose an image from the gallery
